# ✅ 3. Auto-Sync main → dev After Deploy
# File: .github/workflows/sync-main-to-dev.yml

name: Sync main → dev

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SYNC }}

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Fetch and sync
        run: |
          git fetch origin
          git checkout dev || git checkout -b dev origin/main
          git merge origin/main --no-edit || echo "Merge conflict — resolve manually"
          git remote set-url origin https://x-access-token:${{ secrets.SYNC }}@github.com/${{ github.repository }}.git
          git push origin dev
