# ✅ Combined Auto + Manual Tagging Workflow
# File: .github/workflows/tag-release.yml

name: Tag Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Optional: manually enter tag version (e.g., v1.3.0). Leave blank for auto-increment.'
        required: false

  push:
    branches: [main]

jobs:
  tag-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.sync }}

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          latest=$(git tag --sort=-version:refname | head -n 1)
          echo "Latest tag: $latest"
          echo "latest_tag=$latest" >> $GITHUB_OUTPUT

      - name: Determine new tag (manual or auto)
        id: bump
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            echo "new_tag=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            latest=${{ steps.get_tag.outputs.latest_tag }}
            if [ -z "$latest" ]; then
              echo "new_tag=v1.0.0" >> $GITHUB_OUTPUT
            else
              IFS='.' read -r major minor patch <<< "${latest#v}"
              patch=$((patch + 1))
              echo "new_tag=v$major.$minor.$patch" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Create Git Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ steps.bump.outputs.new_tag }}
          git push origin ${{ steps.bump.outputs.new_tag }}

      - name: Notify Slack (optional)
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"🏷️ *New Release:* ${{ steps.bump.outputs.new_tag }} has been created and pushed to \\`main\\` 🚀\"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
